version: 2
updates:
  # Mantain dependencies for Github Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "⬆️ "

  # Mantain dependencies for pub
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
    commit-message:
      prefix: "⬆️ "
    versioning-strategy: increase
