name: keycloak_wrapper
description: Keycloak Single Sign-On (SSO) authentication package for Flutter framework.
version: 1.5.0
repository: https://github.com/fa-fifi/keycloak_wrapper
screenshots:
  - description: "http://localhost:8080/realms/myrealm/account"
    path: screenshots/keycloak-account-console.png
  - description: "http://localhost:8080/admin"
    path: screenshots/keycloak-admin-console.png
topics: [authentication, keycloak, oauth2, openidconnect]

environment:
  sdk: ^3.6.0
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_appauth: ^11.0.0
  flutter_secure_storage: ^10.0.0
  shared_preferences: ^2.5.4

dev_dependencies:
  lint:
