name: keycloak_wrapper
description: Keycloak Single Sign-On (SSO) authentication package for Flutter framework.
version: 0.1.0
repository: https://github.com/fa-fifi/keycloak-wrapper

environment:
  sdk: '>=3.1.2 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_appauth: ^6.0.2
  flutter_secure_storage: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0