name: keycloak_wrapper
description: Keycloak Single Sign-On (SSO) authentication package for Flutter framework.
version: 1.4.6
repository: https://github.com/fa-fifi/keycloak_wrapper
screenshots:
  - description: "Default Keycloak Login Screen"
    path: screenshots/login-screen.png
topics: [ authentication, keycloak, oauth2, openidconnect ]

environment:
  sdk: ^3.6.0
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_appauth: ^10.0.0
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: