name: keycloak_wrapper
description: Keycloak Single Sign-On (SSO) authentication package for Flutter framework.
version: 1.1.2
repository: https://github.com/fa-fifi/keycloak_wrapper
screenshots:
  - description: "Default Keycloak Login Screen"
    path: screenshots/login-screen.png
topics: [ authentication, keycloak, oauth2, openidconnect ]

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  flutter_appauth: ^6.0.6
  flutter_secure_storage: ^9.2.2

dev_dependencies:
  lint:
  test: