name: keycloak_wrapper
description: Keycloak Single Sign-On (SSO) authentication package for Flutter framework.
version: 1.4.4
repository: https://github.com/fa-fifi/keycloak_wrapper
screenshots:
  - description: "Default Keycloak Login Screen"
    path: screenshots/login-screen.png
topics: [ authentication, keycloak, oauth2, openidconnect ]

environment:
  sdk: ">=3.1.2 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_appauth: ^9.0.0
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: